[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
encode_sol_team3 = "C5QhVafpW7JZjLMGj2zbLyGQNxnpgMRJbnNcFyzpis2m"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/fuckthekingcode/WorkSpace/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
